export type Animal = {
  id: string;
  name: string;
  category: 'mammal' | 'bird' | 'reptile' | 'fish' | 'amphibian' | 'insect';
  habitat: string;
  diet: string;
  funFact: string;
  imageUrl: number;
};

export const animals: Animal[] = [
  {
    id: '1',
    name: 'Elephant',
    category: 'mammal',
    habitat: 'Savanna, forest',
    diet: 'Herbivore',
    funFact: 'Elephants can recognize themselves in a mirror!',
    imageUrl: require('../assets/images/animals/elephant.jpg'),
  },
  {
    id: '2',
    name: 'Lion',
    category: 'mammal',
    habitat: 'Savanna, grassland',
    diet: 'Carnivore',
    funFact: "A lion's roar can be heard from 5 miles away!",
    imageUrl: require('../assets/images/animals/lion.jpg'),
  },
  {
    id: '3',
    name: 'Penguin',
    category: 'bird',
    habitat: 'Antarctica, ocean',
    diet: 'Carnivore',
    funFact: 'Penguins can jump as high as 6 feet in the air!',
    imageUrl: require('../assets/images/animals/penguin.jpg'),
  },
  {
    id: '4',
    name: 'Chameleon',
    category: 'reptile',
    habitat: 'Tropical forests',
    diet: 'Carnivore',
    funFact: 'Chameleons can move their eyes independently, giving them a 360-degree view of their surroundings!',
    imageUrl: require('../assets/images/animals/chameleon.jpg'),
  },
  {
    id: '5',
    name: 'Dolphin',
    category: 'mammal',
    habitat: 'Ocean',
    diet: 'Carnivore',
    funFact: 'Dolphins sleep with one eye open!',
    imageUrl: require('../assets/images/animals/dolphin.jpg'),
  },
  {
    id: '6',
    name: 'Giraffe',
    category: 'mammal',
    habitat: 'Savanna',
    diet: 'Herbivore',
    funFact: 'Giraffes have the same number of neck vertebrae as humans - seven!',
    imageUrl: require('../assets/images/animals/giraffe.jpg'),
  },
  {
    id: '7',
    name: 'Frog',
    category: 'amphibian',
    habitat: 'Pond, forest',
    diet: 'Carnivore',
    funFact: 'Some frogs can jump over 20 times their body length!',
    imageUrl: require('../assets/images/animals/frog.jpg'),
  },
  {
    id: '8',
    name: 'Parrot',
    category: 'bird',
    habitat: 'Tropical forest',
    diet: 'Omnivore',
    funFact: 'Some parrots can live for over 80 years!',
    imageUrl: require('../assets/images/animals/parrot.jpg'),
  },
  {
    id: '9',
    name: 'Tiger',
    category: 'mammal',
    habitat: 'Forest, grassland',
    diet: 'Carnivore',
    funFact: 'Tigers have striped skin, not just striped fur!',
    imageUrl: require('../assets/images/animals/tiger.jpg'),
  },
  {
    id: '10',
    name: 'Octopus',
    category: 'fish',
    habitat: 'Ocean',
    diet: 'Carnivore',
    funFact: 'Octopuses have three hearts and blue blood!',
    imageUrl: require('../assets/images/animals/octopus.jpg'),
  },
  {
    id: '11',
    name: 'Koala',
    category: 'mammal',
    habitat: 'Eucalyptus forests',
    diet: 'Herbivore',
    funFact: 'Koalas sleep up to 20 hours a day and have fingerprints similar to humans!',
    imageUrl: require('../assets/images/animals/koala.jpg'),
  },
  {
    id: '12',
    name: 'Kangaroo',
    category: 'mammal',
    habitat: 'Grassland, desert',
    diet: 'Herbivore',
    funFact: 'A newborn kangaroo is only 2.5 centimeters long when it first crawls into its mother\'s pouch!',
    imageUrl: require('../assets/images/animals/kangaroo.jpg'),
  },
  {
    id: '13',
    name: 'Butterfly',
    category: 'insect',
    habitat: 'Gardens, fields, forests',
    diet: 'Nectar',
    funFact: 'Monarch butterflies can travel up to 3,000 miles during migration!',
    imageUrl: require('../assets/images/animals/butterfly.jpg'),
  },
  {
    id: '14',
    name: 'Panda',
    category: 'mammal',
    habitat: 'Bamboo forests',
    diet: 'Herbivore',
    funFact: 'Giant pandas spend 10-16 hours a day eating bamboo and can eat 20-40 pounds of it daily!',
    imageUrl: require('../assets/images/animals/panda.jpg'),
  },
  {
    id: '15',
    name: 'Shark',
    category: 'fish',
    habitat: 'Ocean',
    diet: 'Carnivore',
    funFact: 'Sharks can detect one drop of blood in 25 gallons of water and can sense it from three miles away!',
    imageUrl: require('../assets/images/animals/shark.jpg'),
  },
  {
    id: '16',
    name: 'Owl',
    category: 'bird',
    habitat: 'Forest, grassland',
    diet: 'Carnivore',
    funFact: 'Owls can rotate their heads up to 270 degrees without damaging blood vessels or nerves!',
    imageUrl: require('../assets/images/animals/owl.jpg'),
  },
  {
    id: '17',
    name: 'Bee',
    category: 'insect',
    habitat: 'Gardens, meadows',
    diet: 'Nectar, pollen',
    funFact: 'A honey bee can fly up to 15 miles per hour and visits up to 100 flowers during one collection trip!',
    imageUrl: require('../assets/images/animals/bee.jpg'),
  },
  {
    id: '18',
    name: 'Flamingo',
    category: 'bird',
    habitat: 'Lagoons, lakes',
    diet: 'Omnivore',
    funFact: 'Flamingos get their pink color from the food they eat, which contains carotenoid pigments!',
    imageUrl: require('../assets/images/animals/flamingo.jpg'),
  },
  {
    id: '19',
    name: 'Sloth',
    category: 'mammal',
    habitat: 'Tropical rainforests',
    diet: 'Herbivore',
    funFact: 'Sloths move so slowly that algae can grow on their fur, which helps camouflage them in the forest!',
    imageUrl: require('../assets/images/animals/sloth.jpg'),
  },
  {
    id: '20',
    name: 'Polar Bear',
    category: 'mammal',
    habitat: 'Arctic, sea ice',
    diet: 'Carnivore',
    funFact: 'Polar bears have black skin under their white fur, which helps absorb heat from the sun!',
    imageUrl: require('../assets/images/animals/polar-bear.jpg'),
  },
  {
    id: '21',
    name: 'Peacock',
    category: 'bird',
    habitat: 'Forest, grassland',
    diet: 'Omnivore',
    funFact: 'Male peacocks can have tail feathers that are up to 6 feet long, making up 60% of their total body length!',
    imageUrl: require('../assets/images/animals/peacock.jpg'),
  },
  {
    id: '22',
    name: 'Platypus',
    category: 'mammal',
    habitat: 'Rivers, lakes',
    diet: 'Carnivore',
    funFact: 'Platypuses are one of the few venomous mammals - males have a venomous spur on their hind feet!',
    imageUrl: require('../assets/images/animals/platypus.jpg'),
  },
  {
    id: '23',
    name: 'Seahorse',
    category: 'fish',
    habitat: 'Coral reefs, seagrass beds',
    diet: 'Carnivore',
    funFact: 'Male seahorses are the ones who get pregnant and give birth to baby seahorses!',
    imageUrl: require('../assets/images/animals/seahorse.jpg'),
  },
  {
    id: '24',
    name: 'Axolotl',
    category: 'amphibian',
    habitat: 'Lakes, canals',
    diet: 'Carnivore',
    funFact: 'Axolotls can regenerate lost body parts, including parts of their brain and heart!',
    imageUrl: require('../assets/images/animals/axolotl.jpg'),
  },
  {
    id: '26',
    name: 'Raccoon',
    category: 'mammal',
    habitat: 'Forest, urban areas',
    diet: 'Omnivore',
    funFact: 'Raccoons have incredibly sensitive hands and can identify objects before looking at them!',
    imageUrl: require('../assets/images/animals/raccoon.jpg'),
  },
  {
    id: '27',
    name: 'Hummingbird',
    category: 'bird',
    habitat: 'Gardens, tropical forest',
    diet: 'Omnivore',
    funFact: 'Hummingbirds are the only birds that can fly backwards and upside down!',
    imageUrl: require('../assets/images/animals/hummingbird.jpg'),
  },
  {
    id: '28',
    name: 'Komodo Dragon',
    category: 'reptile',
    habitat: 'Tropical islands',
    diet: 'Carnivore',
    funFact: 'Komodo dragons can eat up to 80% of their body weight in a single meal!',
    imageUrl: require('../assets/images/animals/komodo-dragon.jpg'),
  },
  {
    id: '29',
    name: 'Jellyfish',
    category: 'fish',
    habitat: 'Ocean',
    diet: 'Carnivore',
    funFact: 'Some species of jellyfish are biologically immortal - they can transform back into their juvenile form!',
    imageUrl: require('../assets/images/animals/jellyfish.jpg'),
  },
  {
    id: '30',
    name: 'Praying Mantis',
    category: 'insect',
    habitat: 'Gardens, forests',
    diet: 'Carnivore',
    funFact: 'A praying mantis can turn its head 180 degrees to scan its surroundings!',
    imageUrl: require('../assets/images/animals/praying-mantis.jpg'),
  },
  {
    id: '31',
    name: 'Red-Eyed Tree Frog',
    category: 'amphibian',
    habitat: 'Rainforest',
    diet: 'Carnivore',
    funFact: 'These frogs sleep during the day with their eyes closed, showing only their green body. When threatened, they flash their red eyes to startle predators!',
    imageUrl: require('../assets/images/animals/red-eyed-tree-frog.jpg'),
  },
  {
    id: '33',
    name: 'Monarch Butterfly',
    category: 'insect',
    habitat: 'Gardens, meadows',
    diet: 'Herbivore',
    funFact: 'Monarch butterflies migrate up to 3,000 miles, despite weighing less than a paperclip!',
    imageUrl: require('../assets/images/animals/monarch-butterfly.jpg'),
  },
  {
    id: '34',
    name: 'Manta Ray',
    category: 'fish',
    habitat: 'Ocean',
    diet: 'Carnivore',
    funFact: 'Manta rays have the largest brain of all fish and can recognize themselves in mirrors!',
    imageUrl: require('../assets/images/animals/manta-ray.jpg'),
  },
  {
    id: '35',
    name: 'Toucan',
    category: 'bird',
    habitat: 'Rainforest',
    diet: 'Omnivore',
    funFact: 'A toucan\'s bill is actually very light despite its size - it\'s made of a lightweight protein called keratin!',
    imageUrl: require('../assets/images/animals/toucan.jpg'),
  },
];